"""Shell completion scripts, generated from the live argparse tree so
the command list can never drift from the implementation.

Install:
    beans completions bash > ~/.local/share/bash-completion/completions/beans
    beans completions zsh  > ~/.zfunc/_beans   # with fpath+=(~/.zfunc)
"""

from __future__ import annotations

from beans.utils import BeansError

# Commands whose next positional argument is an account name.
ACCOUNT_COMMANDS = ("spend", "earn", "transfer", "register", "clear",
                    "reconcile")

BASH_TEMPLATE = """\
# bash completion for beans (generated by `beans completions bash`)
_beans() {{
    local cur cmd subs
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    cmd="${{COMP_WORDS[1]}}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "{commands}" -- "$cur") )
        return
    fi
    subs=""
    case "$cmd" in
{cases}
    esac
    if [[ $COMP_CWORD -eq 2 && -n "$subs" ]]; then
        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
        return
    fi
    case "$cmd" in
        {account_cmds})
            local IFS=$'\\n'
            COMPREPLY=( $(compgen -W "$(beans account list --names \\
                2>/dev/null)" -- "$cur") )
            ;;
    esac
}}
complete -F _beans beans
"""

ZSH_TEMPLATE = """\
#compdef beans
# zsh completion for beans (generated by `beans completions zsh`)
_beans() {{
    local -a commands
    commands=({commands})
    if (( CURRENT == 2 )); then
        _describe -t commands 'beans command' commands
        return
    fi
    local cmd=${{words[2]}}
    local -a subs
    case "$cmd" in
{cases}
    esac
    if (( CURRENT == 3 )) && (( ${{#subs}} )); then
        _describe -t subcommands 'subcommand' subs
        return
    fi
    case "$cmd" in
        {account_cmds})
            local -a accounts
            accounts=(${{(f)"$(beans account list --names 2>/dev/null)"}})
            _describe -t accounts 'account' accounts
            ;;
    esac
}}
_beans "$@"
"""


def generate(shell: str, command_map: dict[str, list[str]]) -> str:
    """Render a completion script for `shell` from {command: [subcommand]}."""
    commands = " ".join(sorted(command_map))
    if shell == "bash":
        cases = "\n".join(
            f'        {name}) subs="{" ".join(subs)}" ;;'
            for name, subs in sorted(command_map.items()) if subs
        )
        return BASH_TEMPLATE.format(
            commands=commands,
            cases=cases,
            account_cmds="|".join(ACCOUNT_COMMANDS),
        )
    if shell == "zsh":
        cases = "\n".join(
            f'        {name}) subs=({" ".join(subs)}) ;;'
            for name, subs in sorted(command_map.items()) if subs
        )
        return ZSH_TEMPLATE.format(
            commands=commands,
            cases=cases,
            account_cmds="|".join(ACCOUNT_COMMANDS),
        )
    raise BeansError(f"unsupported shell {shell!r} (expected bash or zsh)")
